Added get posts method with pagination
SGGW-Projekt-Zespolowy/SocialNetworkService.API pull request #47
Opened 2023-06-27 20:32 UTC by kowalczykp01

2023-06-27 21:14 UTC, JWierzbix requested changes

2023-06-27 21:14 UTC, JWierzbix commented on SocialNetworkService.API/Presentation/Controllers/PostsController.cs
> +        [ProducesResponseType(typeof(List<Post>), StatusCodes.Status200OK)]
Generalnie nie powinien być zwracany typ Domain przez nasz endpoint. Zawsze Powinna być jakas klasa/record "response/dto". 

Dodaj klasę, która będzie zawierała wszystko poza polem ModificationDate
Może to być coś w stylu GetPostsByScopeQueryResponse, gdzie w środku będzie lista z obiektami PostResponse

<pre>
public sealed class GetPostsByScopeQueryResponse 
{ 
      public List(PostResponse) Posts {get; set;}
}
</pre>

2023-06-27 21:59 UTC, kowalczykp01 commented on SocialNetworkService.API/Presentation/Controllers/PostsController.cs
> +        [ProducesResponseType(typeof(List<Post>), StatusCodes.Status200OK)]
Poprawione

2023-06-28 00:41 UTC, JWierzbix approved these changes

2023-06-28 15:35 UTC, merged